spring:
  datasource:
    url: jdbc:postgresql://localhost/curr_conv2
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false